# Alacritty Configuration File (https://github.com/alacritty/alacritty)

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size =   12.0

[window]
dimensions = { columns =  180, lines=  55 }

