# windowrule = workspace 1, class:zen
# windowrule = workspace 2, class:.*ghostty
# windowrule = workspace 3, class:obsidian
# Deprecated??
# TODO: investigate
# windowrule = workspace 3, class:steam
#
# windowrule = float, title:.*Extension.*
# windowrule = float, class:steam, title:negative:^(Steam)$
# windowrule = float, initialClass:^(brave-).*$
